on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    name: Update Dunlop0
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        run: curl -X POST https://api.wiseoldman.net/v2/players/dunlop0
