on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-dunlop0:
    name: Update WiseOldMan profiles
    runs-on: ubuntu-latest
    steps:
      - name: Update Dunlop0
        run: curl -X POST https://api.wiseoldman.net/v2/players/dunlop0
      - name: Update IronManitou
        run: curl -X POST https://api.wiseoldman.net/v2/players/IronManitou
      - name: Update IronReAzem
        run: curl -X POST https://api.wiseoldman.net/v2/players/IronReAzem
