on:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update-dunlop0:
    name: Update WiseOldMan profiles
    runs-on: ubuntu-latest
    steps:
      - name: Update Dunlop0
        run: curl -X POST https://api.wiseoldman.net/v2/players/dunlop0
      - name: Update IronManitou
        run: curl -X POST https://api.wiseoldman.net/v2/players/IronManitou
      - name: Update ReAzem
        run: curl -X POST https://api.wiseoldman.net/v2/players/ReAzem
      - name: Update ReAzem1
        run: curl -X POST https://api.wiseoldman.net/v2/players/ReAzem1
      - name: Update pourliverbtw
        run: curl -X POST https://api.wiseoldman.net/v2/players/pourliverbtw
